### ISSUE TITLE
Highlighting of content in native JS loops seems broken.

### ISSUE THREAD

**Issue by mathiasschopmans** [davidrios/jade-tmbundle#38]
Just try the following markup:

```jade
.demo
  - for(i=0; i<5; i++)
    h1 Some text
```

Here's what it looks like in Sublime:
![screenshot](https://cloud.githubusercontent.com/assets/193253/5661507/e88d88f2-972c-11e4-9468-f546a19a6894.png)

**Comment by davidrios** [comment]
I ran some tests here and concluded that it's an incompatibility with the ReactJS package. You have it installed right? It seems the ReactJS package replaces the `source.js` context, and is used instead of the original JavaScript highlighter. If you create a new file, select the ReactJS > JavaScript (JSX) highlighter and try the same code you can confirm it's a bug there. A workaround I found is to add a space after the `<` character.

**Comment by mathiasschopmans** [comment]
Good catch. You're totally right. I removed the React package and it works as expected.
Thanks for investigating in this bug!

**Comment by davidrios** [comment]
No problem. Luckily I also had the ReactJS package installed and so was able catch the bug.
