### ISSUE TITLE
[Feature Request] highlight spacebars #{foo}

### ISSUE THREAD

**Issue by Hongbo-Miao** [davidrios/jade-tmbundle#56]
![1](https://cloud.githubusercontent.com/assets/3375461/10708392/c262cb2a-79d4-11e5-97a5-acbcf71a4edf.png)
I love this Bundle.

Now a lot of people start to use Meteor.
Meteor's spacebars in Jade looks like #{foo}. I would be appreciate if you can highlight this kind of spacebars.
Also in this screenshot, #{showSelectedPlayer.name} shows two kind of color, please just use one highlight color.

Thank you so much!

**Comment by davidrios** [comment]
Sorry, i couldn't quite understand what you want. What kind of highlight should there be on `#{foo}`? As for the `#{showSelectedPlayer.name}` case, this happens because when a #{} block appears in Jade, the highlighting is passed to the JavaScript highlighter, which I have no control of. If you create a new JS file and type `showSelectedPlayer.name` on the first line you will see it is colored in the same way.

**Comment by Hongbo-Miao** [comment]
Hi @davidrios, oh, I mean for things like this #{blabla}, if they can be in a different color, that will be great.

**Comment by dalgard** [comment]
I write my Meteor templates in Jade, too, but I suspect that @Hongbo-Miao is mixing up some concepts around Spacebars and interpolation. Still, it might be nice to have special highlighting of `#{...}`.

In the Meteor version of Jade, the interpolation syntax is converted directly to a Spacebars helper – `{{helper posArg keywordArg=value}}`. This gives it some slightly different semantics, since its contents is not JavaScript, but helper syntax.

**Comment by Hongbo-Miao** [comment]
@dalgard Thanks to make it more clear. :)

**Comment by hongbo-miao** [comment]
Wow, this is my first issue on GitHub!
I realized the issue I opened mostly not make sense. I did mix up some concepts around Spacebars and interpolation at that time.
The web world changed a lot since then. I guess it can be close. Ha
