### ISSUE TITLE
False keywords mess up highlighting

### ISSUE THREAD

**Issue by dalgard** [davidrios/jade-tmbundle#61]
The screenshots below should explain the problem.

(The syntax around `+include` is Meteor-specific, but highlighting works fine there with other words.)

![1-include_class](https://cloud.githubusercontent.com/assets/1209018/10788325/f6a34c20-7d76-11e5-9f94-41ae3bfee624.png)

![2-type_attr](https://cloud.githubusercontent.com/assets/1209018/10788234/9207bdfa-7d76-11e5-828e-62848c6a6bd2.png)

![3-class_attr](https://cloud.githubusercontent.com/assets/1209018/10788237/96a3a446-7d76-11e5-900c-fe4dd5a3e95b.png)

![4-type_attr-last](https://cloud.githubusercontent.com/assets/1209018/10788242/9b5a2f96-7d76-11e5-87a3-6256449a044a.png)

![5-other_keywords](https://cloud.githubusercontent.com/assets/1209018/10788496/3d9e513c-7d78-11e5-9bb5-8d4c96de280c.png)

**Comment by davidrios** [comment]
The problem with this and #56 is that they are conflicting with the official Jade implementation, which is really the focus of this highlighter. The solution would be to add another variant supporting meteor Jade, like the already existing `Jade (Python)`, but since I don't use meteor I really have no reason to maintain it. If anyone feels up to the task, just send me a pull request.

**Comment by dalgard** [comment]
Thanks for the quick response.

I realize that the reason for the blue keyword with the following lack of Jade highlighting is that the JavaScript highlighter takes over. The fifth image shows it very clearly. However – even with vanilla Jade syntax alone – I think that control should be given back to the Jade highlighter after the first space following the keyword.

Isn't this correct? I mean, in regard to regular Jade syntax?

**Comment by bfred-it** [comment]
The latest updated did mess up the normal Jade syntax too, not just custom one.

Example:

    mixin a
      a&attributes(attributes)
        block
      
    +a()(class='demo-only')
      | text


Result on http://jade-lang.com/

<img width="271" alt="screen shot 2015-11-02 at 16 24 22" src="https://cloud.githubusercontent.com/assets/1402241/10878127/7feaeb64-8100-11e5-9f82-eb73fbb3bc5d.png">

Result from jade-tmbundle:

<img width="219" alt="screen shot 2015-11-02 at 16 23 49" src="https://cloud.githubusercontent.com/assets/1402241/10878129/85ea5d42-8100-11e5-8c6a-8914dd1b105c.png">

The thing is that it worked well until the last time I restarted ST3, now my files are unreadable :(

**Comment by davidrios** [comment]
You are using the Babel package, right? The problem is that when I pass
the highlighting to another language, I only get the control back when it stops,
and the Babel JavaScript highlighter have rules for some keywords, like `class`
and `type`, that are greedier than Sublime's default.

It's generally not a problem, as code like:

```jade
input(type=function placeholder='asdfsdf')
```

is invalid Jade anyway, but it can cause issues if some features implemented
by Babel conflicts with your valid Jade code.

@dalgard I included a special case for mixin call with params in the form `name=value`
which should solve your use case.

@bfred-it Your example suffered from the same incompatibility with Babel, but I was
able to improve the matching for mixins, so now it's more accurate and working as expected.

**Comment by bfred-it** [comment]
Yep, that fixed it! Thank you :)
